import { useState } from "react";
import { useApp } from "../context/AppContext";

export default function Report() {
  const { theme, metrics, params, mode, sessionTime, sessionCount, checkins, patients } = useApp();
  const dark = theme === "dark";
  const [exporting, setExporting] = useState(false);
  const [exportType, setExportType] = useState(null);

  const formatTime = (s) => {
    const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60;
    return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;
  };

  const sessionData = {
    mode: mode.toUpperCase(),
    frequency: `${params.freq} Hz`,
    amplitude: `${params.amp} mA`,
    pulseWidth: `${params.pw} µs`,
    breathRate: `${params.br} /min`,
    safetyThreshold: `${params.thresh} mA`,
    sessionDuration: formatTime(sessionTime),
    totalSessions: sessionCount,
    tidalVolume: `${metrics.tidalVol} mL`,
    breathRateLive: `${metrics.breathRate} /min`,
    rms: `${metrics.rms?.toFixed(2)} mA`,
    fatigueIndex: `${metrics.fatigueIndex}%`,
    charge: `${metrics.charge?.toFixed(2)} nC`,
    minuteVent: `${((metrics.tidalVol / 1000) * metrics.breathRate).toFixed(2)} L/min`,
    ieRatio: "1:2",
    stimEfficiency: `${Math.min(100, Math.round((metrics.neuralOutput / params.amp) * 100))}%`,
  };

  const generateCSV = () => {
    setExporting(true); setExportType("csv");
    const rows = [
      ["Parameter", "Value"],
      ...Object.entries(sessionData),
      [],
      ["Check-in History"],
      ["Date", "Time", "Feeling", "Fatigue", "Breathing"],
      ...checkins.slice(0, 10).map(c => [c.date, c.time, c.feel, c.fatigue, c.breath]),
    ];
    const csv = rows.map(r => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `synapse-report-${Date.now()}.csv`; a.click();
    setTimeout(() => { setExporting(false); setExportType(null); }, 1000);
  };

  const generateJSON = () => {
    setExporting(true); setExportType("json");
    const data = { sessionData, checkins, patients: patients.map(p => ({ name: p.name, age: p.age, injury: p.injury, vent: p.vent })), generatedAt: new Date().toISOString() };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `synapse-data-${Date.now()}.json`; a.click();
    setTimeout(() => { setExporting(false); setExportType(null); }, 1000);
  };

  const generatePDF = () => {
    setExporting(true); setExportType("pdf");
    const content = `
SYNAPSE — NEURAL RESPIRATORY PLATFORM
Session Report
Generated: ${new Date().toLocaleString()}
${"=".repeat(50)}

SESSION PARAMETERS
${Object.entries(sessionData).map(([k, v]) => `${k.padEnd(25)} ${v}`).join("\n")}

${"=".repeat(50)}
CHECK-IN HISTORY (Last 5)
${checkins.slice(0, 5).map(c => `${c.date} ${c.time} | Feel: ${c.feel} | Fatigue: ${c.fatigue} | Breath: ${c.breath}`).join("\n") || "No check-ins recorded"}

${"=".repeat(50)}
CLINICAL NOTES
This report was generated by the SYNAPSE Neural Respiratory Platform.
All values are simulated for prototype demonstration purposes.
Consult a qualified clinician before making any therapy decisions.

Project: Non-Invasive Phrenic Nerve Diaphragm Pacing System
Team: Akshhatha S G, Nilofar Fathima R
Guide: Dinesh A
    `;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `synapse-report-${Date.now()}.txt`; a.click();
    setTimeout(() => { setExporting(false); setExportType(null); }, 1000);
  };

  const printReport = () => window.print();

  const card = (bg = "#061a28") => `rounded-lg border p-3 ${dark ? `bg-[${bg}] border-[#0a2535]` : "bg-white border-[#d0e4ef]"}`;

  return (
    <div>
      <div className="mb-4">
        <h1 className="font-display text-[14px] font-bold tracking-[3px] uppercase mb-1" style={{ color: "#00e5ff" }}>Session Report</h1>
        <div className={`text-[11px] font-mono ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>EXPORT · DOWNLOAD · PRINT</div>
      </div>

      {/* Export buttons */}
      <div className={`rounded-lg border p-4 mb-4 ${dark ? "bg-[#061a28] border-[#0a2535]" : "bg-white border-[#d0e4ef]"}`}>
        <div className={`text-[10px] tracking-[2px] uppercase mb-4 font-bold ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>EXPORT OPTIONS</div>
        <div className="grid grid-cols-4 gap-3">
          {[
            { label: "📄 PDF Report", desc: "Full session summary", action: generatePDF, color: "#ff3366", type: "pdf" },
            { label: "📊 CSV Data", desc: "Spreadsheet format", action: generateCSV, color: "#00e5ff", type: "csv" },
            { label: "🗂 JSON Data", desc: "Machine readable", action: generateJSON, color: "#ffd600", type: "json" },
            { label: "🖨 Print", desc: "Browser print dialog", action: printReport, color: "#00ff88", type: "print" },
          ].map((e, i) => (
            <button key={i} onClick={e.action} disabled={exporting}
              className={`rounded-lg border p-4 text-left transition-all hover:-translate-y-1 ${dark ? "border-[#0a2535] bg-[#020c12] hover:border-[#00e5ff]" : "border-[#d0e4ef] bg-gray-50 hover:border-[#0099bb]"}`}>
              <div className="text-[20px] mb-2">{exporting && exportType === e.type ? "⏳" : e.label.split(" ")[0]}</div>
              <div className="font-bold text-[13px] mb-1" style={{ color: e.color }}>{e.label.split(" ").slice(1).join(" ")}</div>
              <div className={`text-[11px] ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>{e.desc}</div>
            </button>
          ))}
        </div>
      </div>

      {/* Session parameters */}
      <div className={`rounded-lg border p-4 mb-4 ${dark ? "bg-[#061a28] border-[#0a2535]" : "bg-white border-[#d0e4ef]"}`}>
        <div className={`text-[10px] tracking-[2px] uppercase mb-4 font-bold ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>SESSION PARAMETERS</div>
        <div className="grid grid-cols-4 gap-3">
          {Object.entries(sessionData).slice(0, 8).map(([k, v]) => (
            <div key={k} className={`rounded-lg border p-3 ${dark ? "bg-[#020c12] border-[#0a2535]" : "bg-gray-50 border-[#d0e4ef]"}`}>
              <div className={`text-[9px] tracking-[1.5px] uppercase mb-1 ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>{k.replace(/([A-Z])/g, " $1").trim()}</div>
              <div className="font-mono text-[15px] font-bold" style={{ color: "#00e5ff" }}>{v}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Physiological metrics */}
      <div className={`rounded-lg border p-4 mb-4 ${dark ? "bg-[#061a28] border-[#0a2535]" : "bg-white border-[#d0e4ef]"}`}>
        <div className={`text-[10px] tracking-[2px] uppercase mb-4 font-bold ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>PHYSIOLOGICAL METRICS</div>
        <div className="grid grid-cols-4 gap-3">
          {Object.entries(sessionData).slice(8).map(([k, v]) => (
            <div key={k} className={`rounded-lg border p-3 ${dark ? "bg-[#020c12] border-[#0a2535]" : "bg-gray-50 border-[#d0e4ef]"}`}>
              <div className={`text-[9px] tracking-[1.5px] uppercase mb-1 ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>{k.replace(/([A-Z])/g, " $1").trim()}</div>
              <div className="font-mono text-[15px] font-bold" style={{ color: "#00ff88" }}>{v}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Check-in history */}
      {checkins.length > 0 && (
        <div className={`rounded-lg border p-4 mb-4 ${dark ? "bg-[#061a28] border-[#0a2535]" : "bg-white border-[#d0e4ef]"}`}>
          <div className={`text-[10px] tracking-[2px] uppercase mb-4 font-bold ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>RECENT CHECK-INS</div>
          <table className="w-full text-[12px]">
            <thead><tr>
              {["Date", "Time", "Feeling", "Fatigue", "Breathing"].map(h => (
                <th key={h} className={`text-left px-3 py-2 text-[10px] tracking-[1px] uppercase border-b ${dark ? "border-[#0a2535] text-[#4a7a90]" : "border-[#d0e4ef] text-[#7aabb8]"}`}>{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {checkins.slice(0, 8).map((c, i) => (
                <tr key={i} className={`border-b ${dark ? "border-[#0a2535]" : "border-[#d0e4ef]"}`}>
                  <td className="px-3 py-2 font-mono">{c.date}</td>
                  <td className="px-3 py-2 font-mono">{c.time}</td>
                  <td className="px-3 py-2">{c.feel}</td>
                  <td className="px-3 py-2">{c.fatigue}</td>
                  <td className="px-3 py-2">{c.breath}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Clinical disclaimer */}
      <div className={`rounded-lg border p-4 ${dark ? "bg-[#061a28] border-[#0a2535]" : "bg-white border-[#d0e4ef]"}`}>
        <div className={`text-[10px] tracking-[2px] uppercase mb-2 font-bold ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>CLINICAL DISCLAIMER</div>
        <div className={`text-[12px] leading-relaxed ${dark ? "text-[#4a7a90]" : "text-[#7aabb8]"}`}>
          This report is generated by the SYNAPSE Neural Respiratory Platform prototype. All waveform data is simulated for demonstration purposes. This system is not FDA-approved and should not be used for actual clinical decision-making without appropriate regulatory approval and clinical validation. Consult a qualified clinician for any therapy decisions.
        </div>
        <div className="mt-3 text-[11px] font-mono" style={{ color: "#00e5ff" }}>
          Project: Non-Invasive Phrenic Nerve Diaphragm Pacing System · Team: Akshhatha S G, Nilofar Fathima R · Guide: Dinesh A
        </div>
      </div>
    </div>
  );
}